### ISSUE TITLE
windows下shell变量似乎会导致一些问题

### ISSUE THREAD

**Issue by with0out** [tracyone/t-vim#2]
我的vimrc是根据你之前的配置改的，然后这次vimdiff更新了一下，发现总会出错，然后发现是这行造成的
`set shell=$SHELL`
是不是这行需要放在`if s:is_win`的else分支里呀？

**Comment by tracyone** [comment]
你的shell是？在vim执行`:echo $SHELL`输出啥？

**Comment by with0out** [comment]
gvim执行`:echo $SHELL`什么也没返回，出错的时候echo也一样没有返回值。
