### ISSUE TITLE
man help会有错误出现,然后在两个分割窗口中同时显示

### ISSUE THREAD

**Issue by tonyho** [tracyone/t-vim#5]
出现的错误为: Error while processing function TracyoneFindMannul[10]..neoman#get_page[30]..<SNR>101_read_page: W10: Change a readonly file

**Comment by tracyone** [comment]
我用的是neoman，所以你应该用Nman命令，比如说，:Nman printf。

你可以执行:PlugStatus查看neoman.vim有没有安装好。

**Comment by tonyho** [comment]
- neoman.vim: OK
直接用:Nman XXX是可以的,但是使用SPACE hm就会有问题.

**Comment by tracyone** [comment]
偶尔的确会出现这个问题，这快捷键和K是一样的功能，就是当c,cpp的时候打开man手册，而vim的时候打开vim help，我会找下原因...
