### ISSUE TITLE
Append bufferline request

### ISSUE THREAD

**Issue by tonyho** [tracyone/t-vim#6]
可以考虑添加bufferline从而切换buffer文件更快速.
[https://github.com/bling/vim-bufferline](url)

**Comment by tracyone** [comment]
哈，我是ctrlp重度用者，现在把几个里右手最近的快捷键都分配给ctrlp了（除了space之外的快捷键），看这里[fuzzy-files-search--string-search](https://github.com/tracyone/t-vim#fuzzy-files-search--string-search)

我用ctrlp切换buffer,mru和file。
你觉得如何？

**Comment by tonyho** [comment]
ctrlp确实不错,但是如果在statusline上面加上buffer list显示, 或者新添加一行用来显示buffer list files, 那么就不需要去搜索然后在切换了,直接一个命令即可搞定.

这个可能是个人习惯. Thanks.

**Comment by tracyone** [comment]
的确是有这种习惯，我习惯了打开很多tab，然后在tab之中切换，既可以用spc+数字切换，也可以用CtrlPBuffer来切换(ctrl-j然后选择，ctrl-t切换或者tab打开)
